- name: parando nginx 
  service: 
   name: nginx 
   state: stopped 
  ignore_errors: true 

- name: remove nginx to centOS 
  yum: 
   name: nginx 
   state: absent 
  when: ansible_distribution == "CentOS"


- name: remove nginx to Debian or ubuntu
  apt: 
   name: nginx 
   state: absent 
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
